#!/usr/bin/env bash

_liq_complete()
{
  local cur args

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  cur=`echo $cur | sed 's/\\\\//g'`
  args="--defaultsFile"
  args="$args --changeLogFile --username --password --url --classpath --driver --contexts --labels --defaultsFile --includeSystemClasspath --logLevel --logFile" 
  
  args="$args status update dropAll dbDoc validate updateTestingRollback"
  if [ -e "$HOME/conf/liquibase.completions" ]; then
    args="$args "`cat "$HOME/conf/liquibase.completions"`
  fi
  COMPREPLY=($(compgen -W "$args " -- "$cur" ))
}



complete -f -F  _liq_complete -o filenames liquibase 
# COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
# COMP_WORDBREAKS=${COMP_WORDBREAKS//=}

